# ─── API Service ──────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: store-api
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "platform.api.selectorLabels" . | nindent 4 }}
